name: msc
channels:
  - pytorch
  - dglteam
  - conda-forge
  - soumith
  - defaults
dependencies:
  - babel=2.10.3
  - ipython=8.6.0
  - json5=0.9.6
  - jupyterlab=3.4.3
  - matplotlib=3.5.1
  - nbconvert=6.5.0
  - numpy=1.23.3
  - opencv=4.6.0
  - pip=22.2.2
  - py-opencv=4.6.0
  - pytorch=1.13.0
  - scipy=1.9.3
  - seaborn=0.12.0
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - pip:
    - cairosvg==2.7.1
    - captum==0.5.0
    - jupyter==1.0.0
    - jupyter-console==6.4.4
    - jupyterlab-widgets==3.0.5
    - kaggle==1.5.12
    - langcodes==3.3.0
    - llvmlite==0.39.1
    - notebook==6.5.2
    - numba==0.56.4
    - pandas==1.5.2
    - quantus==0.3.0
    - regex==2022.8.17
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - shap==0.41.0
    - sklearn==0.0
    - zennit==0.5.0
